env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - jest
  - react
  - "@typescript-eslint"
rules:
  "@typescript-eslint/consistent-type-imports":
    - error
  "@typescript-eslint/no-non-null-assertion":
    - off
  import/prefer-default-export:
    - warn
  import/no-unresolved:
    - error
    - ignore:
        - ^(@utils|@message)/index$
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: true
  eqeqeq:
    - error
overrides:
  - files:
      - "**/*.js"
    rules:
      "@typescript-eslint/no-var-requires":
        - off
  - files:
      - test/**
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
    rules:
      jest/prefer-todo:
        - warn
root: true
settings:
  jest:
    version: 28
  react:
    version: detect
  import/internal-regex: ^(@utils|@message)
  import/resolver:
    node:
      extensions:
        - .d.ts
        - .ts
        - .tsx
        - .js
        - .jsx
        - .json
