env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  semi:
    - error
    - always
  "@typescript-eslint/consistent-type-imports":
    - warn
settings:
  react:
    version: detect
