site_name: GeoFS Plugin System
site_url: https://gpsystem.github.io/gps/

repo_name: gpsystem/gps
repo_url: https://github.com/gpsystem/gps

copyright: Copyright &copy; 2022 GeoFS Plugin System

markdown_extensions:
  - mdx_truly_sane_lists
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Getting started:
      - Installation: getting-started.md
      - License: license.md
  - Contributing:
      - contributing/index.md
      - Style guides:
          - contributing/style/index.md
          - Repo: contributing/style/repo.md
          - Code: contributing/style/code.md
          - Documentation: contributing/style/docs.md
  - Internal:
      - internal.md
      - Docs:
          - api/internal/index.md
          - Utils: api/internal/utils.md
  - Developers:
      - developers/index.md
      - Tutorial:
          - Prerequisites: developers/tutorial/index.md
          - Scaffolding: developers/tutorial/scaffolding.md
          - Creation: developers/tutorial/creation.md
      - API Docs:
          - api/index.md
